---
# tasks file for mac_app_store

- name: Install applications from App Store
  community.general.mas:
    id: "{{ item.id }}"
    state: "{{ item.state }}"
  with_items:
    "{{ install_applications_from_appstore }}"