# Update homebrew and upgrade all packages

- name: Update homebrew
  community.general.homebrew:
    update_homebrew: yes

- name: install  homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_installed_packages }}"