---
# tasks file for homebrew_cask
- name: Update homebrew cask.
  homebrew_cask:
    update_homebrew: yes

- name: installed docker
  homebrew_cask:
    name: docker

- name: installed google chrome
  homebrew_cask:
    name: google-chrome

- name: installed visual studio code
  homebrew_cask:
    name: visual-studio-code

- name: installed zoom
  homebrew_cask:
    name: zoom

- name: installed notion
  homebrew_cask:
    name: notion

- name: installed postman
  homebrew_cask:
    name: postman

- name: installed virtualbox
  homebrew_cask:
    name: virtualbox


- name: installed vagrant 
  homebrew_cask:
    name: vagrant

