---
# tasks file for homebrew_cask

# - name: Update homebrew cask.
#   homebrew_cask:
#     update_homebrew: yes


- name: installed homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    "{{ installed_cask_packages }}"