---
# vars file for homebrew
homebrew_enabled_repositories:
  - hashicorp/tap

homebrew_installed_packages:
  - ansible
  - cask
  - wget
  - git
  - mas
  - ca-certificates
  - cfssl
  - kind
  - kubernetes-cli
  - minikube
  - python
  - pyenv
  - go
  - hashicorp/tap/terraform
